export enum documents {
  brands = 'brands',
  paints = 'paints',
  users = 'users',
  audit_log = 'audit_log',
  user_color_images = 'user_color_images',
  image_color_picks = 'image_color_picks',
  color_searches = 'color_searches',
  palettes = 'palettes',
  palettes_paints = 'palettes_paints',
  wishlist = 'wishlist',
  inventory = 'inventory',
  category = 'category',
  pending_paint_submissions = 'pending_paint_submissions',
}
